language: node_js
node_js:
  - "8"

sudo: false

branches:
   only:
   - master

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

cache:
  yarn: true
  directories:
    - ".eslintcache"
    - "node_modules"

script:
  # nothing to do
  - true

deploy:
  provider: npm
  email: ${NPM_EMAIL}
  api_key: ${NPM_API_KEY}
  on:
    tags: true
